package system;

import sunset.Game;

//Handles and executes orders generated by entities

public class OrderSystem extends BaseSystem {

	public OrderSystem(Game g) {super(g);}

	public void tick() 
	{
		
	}
	
}
